### ISSUE TITLE
discord-rpc rpath is changed in the ebuild

### ISSUE THREAD

**Issue by natimerry** [an-anime-team/aagl-ebuilds#2]
The ebuild changes the `rpath` of the discord-rpc binary (which is used to scan for libraries in the folder discord-rpc is in) using
`chrpath -d "squashfs-root/public/discord-rpc/discord-rpc" || die "Patching Library Failed"`

This completely breaks the discord-rpc. I would suggest 2 potential fixes:-

1. Getting rid of the `chrpath`
2. Writing a separate ebuild for libdiscord-rpc and installing the library to `/usr/lib` or `/lib` (needs to be tested, although should work)

**Comment by Schievel1** [comment]
This was put in the ebuild before I started maintaining them, so bear with me here. 
So, what I am getting from this is: I guess in the normal Appimage discord-rpc looks inside the Appimage for those libraries, and the rpath is pointing into somewhere in the Appimage? And since we do not install those libraries in the ebuild, not doing the chrpath would not fix this, would it?
I think the right way would be to make another ebuild for libdiscord-rpc like you are suggesting in 2 and putting some optfeature suggestion into the launchers ebuild. I will look into this.

How is the build in the AUR doing this, btw?

Edit: So if that is a file the launcher needs, it should just be installed into `/usr/lib/an-anime-game-launcher/public` like all the other files that are in `squashfs-root/public/` in the AppImage, shouldn't it? I do not really understand what this chrpath line was for in the first place. 
Anyway, with the current ebuild the line `doins -r "squashfs-root/public"` installs everything (including `public/discord-rpc/libdiscord-rpc.so`) in the Appimages `public` folder into  `/usr/lib/an-anime-game-launcher-bin`.  
So I guess because of the `chrpath` before the rpath for `discord-rpc` was deleted and so it is looking into some standard folder like `/usr/lib`. 

We either install `libdiscord-rpc.so` into `/usr/lib` or we get rid of the `chrpath` line and leave everything else as it is. I prefer the latter, I guess the original `rpath` that `chrpath` removed was `./` but we need to check. (or you tell me)

// edit edit: I see you cloned this repo doing it yourself. If you need any help, let me know,   I am happy to help. 
because judging from your commits you seem to have some trouble with the ebuilds install functions. (e. g. You are doing discord-rpc mit doexe, which gives it 755 permissions, then you overwrite that again with doins then you set permissions again to 755)

**Comment by natimerry** [comment]
> Anyway, with the current ebuild the line doins -r "squashfs-root/public" installs everything (including public/discord-rpc/libdiscord-rpc.so) in the Appimages public folder into /usr/lib/an-anime-game-launcher-bin.
So I guess because of the chrpath before the rpath for discord-rpc was deleted and so it is looking into some standard folder like /usr/lib.

No, the discord-rpc doesnt look in `/usr/lib` as `chrpath` seems to remove all ability to scan for libraries. This seems to have been added by @ShinobuNarusaka to mitigate a security warning caused by portage.

Making an pull request with necessary fixes to the ebuild and a new discord-rpc binary in `${FILESDIR}` which doesnt raise security issues.

**Comment by natimerry** [comment]
> edit edit: I see you cloned this repo doing it yourself. If you need any help, let me know, I am happy to help.
because judging from your commits you seem to have some trouble with the ebuilds install functions. (e. g. You are doing discord-rpc mit doexe, which gives it 755 permissions, then you overwrite that again with doins then you set permissions again to 755)

For some reason that wasnt working

**Comment by Schievel1** [comment]
No need to close this until the PR is merged.
